aliases:
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays:
    eza:
        enableAliases: true
        git: true
packages:
    - helix
    - thefuck
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
    - starship
    - bat
    - neovim
    - btop
    - atuin
    - eza
shell: zsh
systems:
    - arch: x86_64
      home: ""
      hostname: macmeh.local
      os: darwin
      user:
        email: jsievert@gmail.com
        name: Jason Sievert
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: jason
      username: jason
track: nixos-unstable
unfree: true
users: []
