aliases:
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
    wtf: thefuck
allow_broken: false
auto_gc: true
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: false
    autopull: true
    autopush: false
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - kubectl
    - argocd
    - terraform
    - sops
    - age
    - krew
    - kubernetes-helm
    - wireshark
    - vault
    - talosctl
    - alejandra
    - du-dust
    - fd
    - procs
    - zoxide
    - broot
    - bat
    - deno
    - hugo
    - ansible
    - ansible-lint
    - rustc
    - cargo
    - rustfmt
    - rust-analyzer
    - ripgrep
    - lima
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - /usr/local/bin
    - /opt/homebrew/bin
    - /Applications/Visual Studio Code.app/Contents/Resources/app/bin
programs:
    - thefuck
    - topgrade
    - jq
    - vscode
    - gh
    - dircolors
    - starship
    - bat
    - neovim
    - btop
    - atuin
    - eza
    - fzf
    - k9s
    - alacritty
    - mcfly
    - navi
    - nix-index
shell: zsh
systems:
    - arch: x86_64
      home: ""
      hostname: macmeh.local
      os: darwin
      user:
        email: jsievert@gmail.com
        name: Jason Sievert
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: jason
      username: jason
    - arch: x86_64
      home: ""
      hostname: nixos
      os: linux
      user:
        email: jsievert@gmail.com
        name: Jason Sievert
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: jason
      username: jason
track: nixos-unstable
unfree: true
users: []
